Register Kubernetes ELB in DNS
Financial-Times/coco-elb-dns-registrator pull request #9
Opened 2017-02-10 11:42 UTC by sbuliarca

**# DO NOT MERGE until we migrate to Kubernetes fully**

2017-02-10 12:33 UTC, davidbalazs93 commented on main.go
> +		log.Fatalf("ERROR - No ingress address found for LB service '%s'", conf.kubeLbService)
just a heads up for this log: it will do an os.Exit(1) in the background, is this the desired behaviour? if yes, leave it as it is now.

2017-02-10 12:43 UTC, sbuliarca commented on main.go
> +		log.Fatalf("ERROR - No ingress address found for LB service '%s'", conf.kubeLbService)
Yep, that's exactly the behavior I want, as I start this as Job that will keep creating the pod until it won't fail.

2017-02-10 15:36 UTC, davidbalazs93 commented on main.go
> +		log.Fatalf("ERROR - No ingress address found for LB service '%s'", conf.kubeLbService)
ok :)

2017-02-10 15:37 UTC, davidbalazs93 approved these changes

2017-02-15 12:19 UTC, tamas-molnar requested changes
Blocking PR so it can't be merged.

2017-03-06 10:16 UTC, davidbalazs93 requested changes
The code is ok, but I will block this PR so it cannot be merged

2018-02-16 11:08 UTC, kovacshuni commented
what can we do with this one?

2018-02-16 12:11 UTC, sbuliarca commented
We'll need to merge them, once we'll decommission coco

2018-05-03 14:18 UTC, tamas-molnar approved these changes

2018-05-03 14:18 UTC, merged